// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW8EnUTmcdV_xgRLstuUoeyJ_7olU7S4o',
    appId: '1:478526312567:web:4930c725cabfcecbb2b672',
    messagingSenderId: '478526312567',
    projectId: 'emtech-be4d4',
    authDomain: 'emtech-be4d4.firebaseapp.com',
    storageBucket: 'emtech-be4d4.firebasestorage.app',
    measurementId: 'G-F1PNW3NDJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtAGygPzHwGO2AIWmx1GZ1i9AQfSW4kwc',
    appId: '1:478526312567:android:01227630f90b93e0b2b672',
    messagingSenderId: '478526312567',
    projectId: 'emtech-be4d4',
    storageBucket: 'emtech-be4d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB40yJBL4ZPLxCziayj59u6GV41xPSMukE',
    appId: '1:478526312567:ios:83c069c3c47fc2dfb2b672',
    messagingSenderId: '478526312567',
    projectId: 'emtech-be4d4',
    storageBucket: 'emtech-be4d4.firebasestorage.app',
    iosClientId: '478526312567-e6folqlvl9113dckgtl4vkqe4bf0rgjr.apps.googleusercontent.com',
    iosBundleId: 'com.emtech.emtechSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB40yJBL4ZPLxCziayj59u6GV41xPSMukE',
    appId: '1:478526312567:ios:83c069c3c47fc2dfb2b672',
    messagingSenderId: '478526312567',
    projectId: 'emtech-be4d4',
    storageBucket: 'emtech-be4d4.firebasestorage.app',
    iosClientId: '478526312567-e6folqlvl9113dckgtl4vkqe4bf0rgjr.apps.googleusercontent.com',
    iosBundleId: 'com.emtech.emtechSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW8EnUTmcdV_xgRLstuUoeyJ_7olU7S4o',
    appId: '1:478526312567:web:a0881df4fe62e34eb2b672',
    messagingSenderId: '478526312567',
    projectId: 'emtech-be4d4',
    authDomain: 'emtech-be4d4.firebaseapp.com',
    storageBucket: 'emtech-be4d4.firebasestorage.app',
    measurementId: 'G-E9ZWRSF374',
  );
}
